# Generated by Django 3.1.1 on 2020-10-02 20:33

import apps.ecauth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ecuser',
            managers=[
                ('objects', apps.ecauth.models.UserManager()),
            ],
        ),
    ]
